---

app:
  container_name: app
  build: .
  command: npm start
  ports:
    - "3000:3000"
  volumes:
    - .:/payment-gateway
  links:
    - mysql
    - redis
redis:
  container_name: redis
  image: redis:2.8
  ports:
    - "6379:6379"
mysql:
  container_name: mysql
  image: mysql:5.7
  ports:
    - "3306:3306"
  environment:
    MYSQL_DATABASE: payment_gateway
    MYSQL_ROOT_PASSWORD: sunday